### ISSUE TITLE
model files

### ISSUE THREAD

**Issue by liberqi** [truonghoangthuan/django-vietnamese-personal-card-ocr#1]
Can you provide “transformerocr.pth” model files?  
thank you very much

**Comment by truonghoangthuan** [comment]
> Can you provide “transformerocr.pth” model files?
> thank you very much

Hello liberqi, you can go to this [https://github.com/truonghoangthuan/django-vietnamese-id-card-ocr](url) to download the model files.

**Comment by truonghoangthuan** [comment]
> Can you provide “transformerocr.pth” model files?
> thank you very much

Hello @liberqi, you can go to this [link](https://onedrive.live.com/?authkey=%21APJLLUUHIcwp7Is&id=E39A8279F4D830FB%21156635&cid=E39A8279F4D830FB) to download model files
